name: Perform checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [Ubuntu, macOS, windows]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-features --all-targets
    - name: Run tests
      run: cargo test --verbose --all-features --all-targets
    - name: Build examples
      run: cargo test --examples
  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add clippy
    - run: cargo clippy
  deny:
    name: Run cargo-deny
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        command: check
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
    - uses: actions/checkout@v3
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check
  semver-checks:
    name: Semver checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: obi1kenobi/cargo-semver-checks-action@v2
